[12, 32, 53, 33, 32, 66, 52, 84, 54, 88]
None


In [11]:
import numpy as np
my_list = np.random.randint(10, size=10)
my_list

array([1, 3, 3, 1, 4, 8, 2, 1, 3, 7])

In [12]:
np.sort(my_list)

array([1, 1, 1, 2, 3, 3, 3, 4, 7, 8])

In [13]:
my_list[::-1].sort()
my_list

array([8, 7, 4, 3, 3, 3, 2, 1, 1, 1])